### ISSUE TITLE
ImportError: cannot import name 'SteamID' from 'steam.abc'

### ISSUE THREAD

**Issue by ingmarinho** [Gobot1234/steam-ext-csgo#12]
So after the last patch you did a new import error came up.

(Still using the example script)

Traceback (most recent call last):
  File "d:\Dev\Repos\medal-bot\testing python\main.py", line 6, in <module>
    from steam.ext import commands, csgo
  File "D:\Dev\Repos\medal-bot\testing python\venv\Lib\site-packages\steam\ext\csgo\__init__.py", line 11, in <module>
    from .client import *
  File "D:\Dev\Repos\medal-bot\testing python\venv\Lib\site-packages\steam\ext\csgo\client.py", line 13, in <module>
    from ...abc import Message, SteamID
ImportError: cannot import name 'SteamID' from 'steam.abc' (D:\Dev\Repos\medal-bot\testing python\venv\Lib\site-packages\steam\abc.py)

Am I missing something?

**Comment by Gobot1234** [comment]
Gosh I hate breaking changes 😉. Fix incoming
