### ISSUE TITLE
ModuleNotFoundError: No module named 'steam.protobufs.msg'

### ISSUE THREAD

**Issue by ingmarinho** [Gobot1234/steam-ext-csgo#13]
Traceback (most recent call last):
  File "d:\Dev\Repos\medal-bot\testing python\main.py", line 6, in <module>
    from steam.ext import commands, csgo
  File "D:\Dev\Repos\medal-bot\testing python\venv\Lib\site-packages\steam\ext\csgo\__init__.py", line 10, in <module>
    from .backpack import *
  File "D:\Dev\Repos\medal-bot\testing python\venv\Lib\site-packages\steam\ext\csgo\backpack.py", line 22, in <module>
    from .protobufs import base, econ, struct_messages
  File "D:\Dev\Repos\medal-bot\testing python\venv\Lib\site-packages\steam\ext\csgo\protobufs\__init__.py", line 7, in <module>
    from ....protobufs.msg import GCProtobufMessage
ModuleNotFoundError: No module named 'steam.protobufs.msg'

well... 😂

**Comment by Gobot1234** [comment]
This worked when I tested it, what does python -m steamio print?

**Comment by ingmarinho** [comment]
> This worked when I tested it, what does python -m steamio print?

(venv) PS D:\Dev\Repos\medal-bot\testing python> python -m steamio  
D:\Dev\Repos\medal-bot\testing python\venv\Scripts\python.exe: No module named steamio

**Comment by Gobot1234** [comment]
Sorry try python -m steam

**Comment by ingmarinho** [comment]
> Sorry try python -m steam

i was using python 3.11 smh

but now:

raceback (most recent call last):
  File "d:\Dev\Repos\medal-bot\testing python\main.py", line 69, in <module>
    asyncio.run(main())
  File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "d:\Dev\Repos\medal-bot\testing python\main.py", line 66, in main
    await bot.start("-------", "-------")
AttributeError: 'MyBot' object has no attribute 'start'

**Comment by Gobot1234** [comment]
start() has been removed from the Client, you now just call .login to achieve the same effect (since all logging in requires a connection to a CM)
