### ISSUE TITLE
Problem with install

### ISSUE THREAD

**Issue by NikittyS** [Gobot1234/steam-ext-csgo#9]
Hello. I can't install this ext. Can you help?

```
Collecting steam-ext-csgo@ git+https://github.com/Gobot1234/steam-ext-csgo@main
  Cloning https://github.com/Gobot1234/steam-ext-csgo (to revision main) to /private/var/folders/56/m1nqtvws3vx24gy0_yzn_w300000gn/T/pip-install-ak0_0um8/steam-ext-csgo_0315336f28314a959d035229c738a736
  Running command git clone --filter=blob:none --quiet https://github.com/Gobot1234/steam-ext-csgo /private/var/folders/56/m1nqtvws3vx24gy0_yzn_w300000gn/T/pip-install-ak0_0um8/steam-ext-csgo_0315336f28314a959d035229c738a736
  Resolved https://github.com/Gobot1234/steam-ext-csgo to commit 95586d8b567b5dfc92e0cf1b54e3ae8824c97139
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      Traceback (most recent call last):
        File "/Users/nikitty/Desktop/git/steambot/env/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/Users/nikitty/Desktop/git/steambot/env/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/nikitty/Desktop/git/steambot/env/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/private/var/folders/56/m1nqtvws3vx24gy0_yzn_w300000gn/T/pip-build-env-mtunq753/overlay/lib/python3.9/site-packages/poetry/core/masonry/api.py", line 43, in prepare_metadata_for_build_wheel
          poetry = Factory().create_poetry(Path(".").resolve(), with_dev=False)
        File "/private/var/folders/56/m1nqtvws3vx24gy0_yzn_w300000gn/T/pip-build-env-mtunq753/overlay/lib/python3.9/site-packages/poetry/core/factory.py", line 43, in create_poetry
          raise RuntimeError("The Poetry configuration is invalid:\n" + message)
      RuntimeError: The Poetry configuration is invalid:
        - Additional properties are not allowed ('group' was unexpected)
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by Gobot1234** [comment]
This should be fixed now, I've changed the build backend temporarily to poetry-core's latest alpha version. Thanks for the report.
